### ISSUE TITLE
增加互斥选择分开计算count

### ISSUE THREAD

**Issue by hubin920218** [joker-fu/EasyPhotos#1]
使用demo
![image](https://user-images.githubusercontent.com/30428545/61784546-796d7c80-ae3c-11e9-9720-cf33b4faa18d.png)
增加代码
![image](https://user-images.githubusercontent.com/30428545/61784587-8f7b3d00-ae3c-11e9-807d-5cb4e7e34b90.png)

![image](https://user-images.githubusercontent.com/30428545/61784626-a28e0d00-ae3c-11e9-956b-7a3b9cf93cd7.png)
![image](https://user-images.githubusercontent.com/30428545/61784646-ab7ede80-ae3c-11e9-929b-116ae3c6db5e.png)

![image](https://user-images.githubusercontent.com/30428545/61784695-bcc7eb00-ae3c-11e9-8ffd-99ff7ef26df6.png)

![image](https://user-images.githubusercontent.com/30428545/61784728-cfdabb00-ae3c-11e9-8dbf-3a78370f34fb.png)

谨供大佬参考

**Comment by joker-fu** [comment]
@hubin920218 已采纳
