### ISSUE TITLE
complexSelector 可选数量有问题 

### ISSUE THREAD

**Issue by twlk-jzy** [joker-fu/EasyPhotos#13]
比如我设置了视频和图片一起显示  视频只可选 1个   图片可选9个   当我选择 图片后  图片 只能选择 8个   理论上我都选择图片类型了  应该能选择9个 才对   而选择 视频  右上角应该是选中的数量/最大可选择的视频数量

**Comment by joker-fu** [comment]
理解不一样，库里面的逻辑就是1+9=10的关系
