### ISSUE TITLE
可以提供下兼容10 ucrop包吗

### ISSUE THREAD

**Issue by abnerYanghf** [joker-fu/EasyPhotos#17]

**Comment by joker-fu** [comment]
没太明白你的诉求，现在Ucrop就是兼容10的了

**Comment by abnerYanghf** [comment]
ucrop下两个Task类,BitmapCropTask BitmapLoadTask加载是直接报错的

**Comment by abnerYanghf** [comment]
demo不报错,是因为声明的继续使用android:requestLegacyExternalStorage="true"

**Comment by joker-fu** [comment]
我意思是我现在是直接用的Ucrop的依赖，我记得他们最新的是兼容了的。另外之前我自己改了一个版本你可以试试（   api 'com.joker.HuanTanSheng:UCrop:andX-2.5.1'）
