### ISSUE TITLE
拍摄视频不能使用系统原生的好像？

### ISSUE THREAD

**Issue by pengjunhong** [joker-fu/EasyPhotos#2]

**Comment by joker-fu** [comment]
是的，没有此功能

**Comment by pengjunhong** [comment]
发现一个新的问题，就是如果当内存吃紧的时候 调用系统的拍照 会出现闪白屏 然后调起自定义的拍照页面。
demo中就可以模拟这个场景：将选择图片以及拍照的回调中，列表clear的先注释掉，模拟页面内存吃紧的情况，然后连续从相册中，选择10次9张图片，之后调用系统拍照，就会出现上门描述的问题。

**Comment by joker-fu** [comment]
clear 指的是哪块？你是说的selectedPhotoList.clear()? 我选择了这么多（分别如下图），然后打开系统相机没有复现出来。有异常日志么？
![image](https://user-images.githubusercontent.com/20105457/71427642-bd1f2780-26f5-11ea-88a5-92c2beef5eb1.png)

![image](https://user-images.githubusercontent.com/20105457/71427751-cbba0e80-26f6-11ea-995d-05c9b7cff50d.png)

![image](https://user-images.githubusercontent.com/20105457/71427953-6c5cfe00-26f8-11ea-82ac-08e1c6049907.png)

**Comment by pengjunhong** [comment]
恩 手机性能好 比较难模拟出来 ，你试下开发者选项中开启不保留活动，然后问题就很容易模拟了。
