### ISSUE TITLE
引入运行出现错误

### ISSUE THREAD

**Issue by pengbig** [joker-fu/EasyPhotos#6]
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/jufengchuxing/.gradle/caches/transforms-2/files-2.1/b42617ed42f3c15b78cda4c19c52af6a/jetified-EasyPhotos-andX-2.5.2/res/values/values.xml:93:5-100:25: AAPT: error: resource attr/easy_iconSize (aka com.jufcx.hurricane:attr/easy_iconSize) not found.

  compileSdkVersion = 29
    buildToolsVersion = '29.0.2'
    minSdkVersion = 19
    targetSdkVersion = 29
    appTargetSdkVersion = 29
    appSourceCompatibility = 1.8

**Comment by sunywhehe** [comment]
I also met the same problem, please help to have a look

compileSdkVersion = 29
buildToolsVersion = '29.0.3'

**Comment by keegan-z** [comment]
楼上+1

**Comment by joker-fu** [comment]
@DeBugZhou @pengbig @DeBugZhou 已解决
