### ISSUE TITLE
真机实测Android10手机照片路径无效

### ISSUE THREAD

**Issue by q88qaz** [joker-fu/EasyPhotos#7]
真机实测Android10手机照片路径无效，返回照片路径（包括压缩路径）是：media://conten/img01
这个bug请问何时修复？

**Comment by q88qaz** [comment]
机型华为畅享5

**Comment by joker-fu** [comment]
Android 10 是返回的uri

**Comment by AndroidNullPointException** [comment]
清单文件 application 加上这句话android:requestLegacyExternalStorage="true" 在android10可以获取到路径地址 
但是只临时解决方案 android11就完全不能用了
以上方法仅限作者没有判断的情况 如果作者判断了版本android10返回uri 那就不起作用了 请修改源码
当然最好的方式还是尽快适配 拼接uri来获取

**Comment by joker-fu** [comment]
现在是做了Android10的兼容的，没明白你具体是什么意思

**Comment by AndroidNullPointException** [comment]
> 现在是做了Android10的兼容的，没明白你具体是什么意思

哦哦 那个是给提问的人回答的 我这是临时解决方案

**Comment by DeBugZhou** [comment]
Android10 如果不剪裁的话 返回的是uri的路径 需要获取绝对路径的话 先把path转化成uri 在调用
 public String getRealPathFromUri(Context context, Uri contentUri) {
        Cursor cursor = null;
        try {
            String[] proj = {MediaStore.Images.Media.DATA};
            cursor = context.getContentResolver().query(contentUri, proj, null, null, null);
            int column_index = cursor.getColumnIndexOrThrow(MediaStore.Images.Media.DATA);
            cursor.moveToFirst();
            return cursor.getString(column_index);
        } finally {
            if (cursor != null) {
                cursor.close();
            }
        }
    }
把Uri转化成真实路径 就可以了
